import { Check, User, Bot, Download } from 'lucide-react'
import type { Agent } from '../data/agents'
import { advantageFor } from '../data/advantage'

// The TermiX "Agent Advantage Report": three real tasks, agent vs.
// doing it yourself, on time / cost / outcome.
export default function AdvantageReport({ agent }: { agent: Agent }) {
  const tasks = advantageFor(agent)
  const total = tasks.reduce((s, t) => s + t.rows.length, 0)
  const wins = tasks.reduce((s, t) => s + t.rows.filter((r) => r.agentWins).length, 0)

  function downloadReport() {
    let md = `# Agent Advantage Report — ${agent.name}\n\n`
    md += `- Agent: ${agent.name} (@${agent.handle}, ERC-8004 #${agent.agentId})\n`
    md += `- Category: ${agent.category}\n`
    md += `- Reputation: ${agent.reputation}/100 · ${agent.hires} hires · ${agent.reviews} on-chain reviews\n`
    md += `- Track record window: ${agent.window}\n`
    md += `- Verdict: ${Math.round((wins / total) * 100)}% of measures favour the agent across ${tasks.length} tasks\n\n`
    tasks.forEach((t, i) => {
      md += `## Task ${i + 1}: ${t.task}\n\n${t.context}\n\n`
      md += `| Dimension | Yourself | ${agent.name} | Winner |\n| --- | --- | --- | --- |\n`
      t.rows.forEach((r) => {
        md += `| ${r.dimension} | ${r.manual} | ${r.agent} | ${r.agentWins ? agent.name : 'tie/you'} |\n`
      })
      md += `\n`
    })
    md += `\n_Generated by Proxima · comparison uses ${agent.name}'s on-chain track record. Replace with your own results after hiring._\n`
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `agent-advantage-${agent.handle.replace(/\W+/g, '-')}.md`
    document.body.appendChild(a)
    a.click()
    a.remove()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="mt-4">
      <div
        className="mb-4 flex items-center justify-between rounded-xl border px-4 py-3"
        style={{ background: 'var(--color-surface-2)', borderColor: 'var(--color-line)' }}
      >
        <div>
          <div className="text-[13px] font-600" style={{ color: 'var(--color-fg)' }}>
            Is it worth hiring?
          </div>
          <div className="text-[11.5px]" style={{ color: 'var(--color-muted)' }}>
            {wins} of {total} measures favour the agent across 3 tasks
          </div>
        </div>
        <div className="tabular font-display text-[24px] font-700" style={{ color: 'var(--color-pos)' }}>
          {Math.round((wins / total) * 100)}%
        </div>
      </div>

      <div className="space-y-4">
        {tasks.map((t, i) => (
          <div key={i} className="rounded-xl border p-4" style={{ background: 'var(--color-surface-2)', borderColor: 'var(--color-line)' }}>
            <div className="mb-0.5 flex items-center gap-2">
              <span className="tabular font-mono text-[11px]" style={{ color: 'var(--color-faint)' }}>
                T{i + 1}
              </span>
              <h4 className="text-[13.5px] font-600" style={{ color: 'var(--color-fg)' }}>
                {t.task}
              </h4>
            </div>
            <p className="mb-3 text-[11.5px]" style={{ color: 'var(--color-faint)' }}>
              {t.context}
            </p>

            <div className="overflow-hidden rounded-lg border" style={{ borderColor: 'var(--color-line)' }}>
              <div className="grid grid-cols-[64px_1fr_1fr] text-[10.5px] font-600 uppercase tracking-wide" style={{ background: 'var(--color-surface)', color: 'var(--color-faint)' }}>
                <div className="px-3 py-2" />
                <div className="flex items-center gap-1 px-3 py-2 border-l" style={{ borderColor: 'var(--color-line)' }}>
                  <User size={11} /> Yourself
                </div>
                <div className="flex items-center gap-1 border-l px-3 py-2" style={{ borderColor: 'var(--color-line)' }}>
                  <Bot size={11} style={{ color: 'var(--color-accent)' }} /> {agent.name}
                </div>
              </div>
              {t.rows.map((r) => (
                <div
                  key={r.dimension}
                  className="grid grid-cols-[64px_1fr_1fr] border-t text-[11.5px]"
                  style={{ borderColor: 'var(--color-line)' }}
                >
                  <div className="px-3 py-2.5 font-600" style={{ color: 'var(--color-muted)' }}>
                    {r.dimension}
                  </div>
                  <div className="border-l px-3 py-2.5" style={{ borderColor: 'var(--color-line)', color: 'var(--color-muted)' }}>
                    {r.manual}
                  </div>
                  <div
                    className="flex items-start gap-1.5 border-l px-3 py-2.5"
                    style={{
                      borderColor: 'var(--color-line)',
                      color: r.agentWins ? 'var(--color-fg)' : 'var(--color-muted)',
                      background: r.agentWins ? 'color-mix(in srgb, var(--color-pos) 7%, transparent)' : 'transparent',
                    }}
                  >
                    {r.agentWins && <Check size={12} className="mt-0.5 shrink-0" style={{ color: 'var(--color-pos)' }} />}
                    <span>{r.agent}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      <button
        onClick={downloadReport}
        className="pressable mt-4 flex w-full items-center justify-center gap-2 rounded-xl border py-2.5 text-[12.5px] font-600"
        style={{ borderColor: 'var(--color-line-strong)', color: 'var(--color-fg)' }}
      >
        <Download size={14} /> Download report (Markdown)
      </button>

      <p className="mt-3 text-[11px] leading-relaxed" style={{ color: 'var(--color-faint)' }}>
        Comparison uses this agent's on-chain track record over {agent.window}. Hire it and the same measures update from
        your own results.
      </p>
    </div>
  )
}
